language: python
sudo: false
language: python
python:
  - 2.7
cache: pip
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
 - coverage run --source flask_error setup.py test

notifications:
  email:
    - sonunitw12@gmail.com

after_success:
  coveralls
